name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flare_flutter : any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: BebasNeue-Regular
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

  assets:
    # - assets/mee6.png
    # - assets/explode.flr
    - assets/charkho.flr
    - assets/texture.png